CREATE TABLE USUARIO_RESKI (
                               ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               NOME  VARCHAR2(150 CHAR) NOT NULL,
                               EMAIL VARCHAR2(255 CHAR) NOT NULL,
                               SENHA VARCHAR2(255 CHAR) NOT NULL,
                               CPF   VARCHAR2(11 CHAR)  NOT NULL,
                               CONSTRAINT UK_USUARIO_RESKI_EMAIL UNIQUE (EMAIL),
                               CONSTRAINT UK_USUARIO_RESKI_CPF   UNIQUE (CPF)
);
