CREATE TABLE TRILHA_RESKI (
                              ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              STATUS      VARCHAR2(100 CHAR)   NOT NULL,
                              CONTEUDO    VARCHAR2(4000 CHAR)  NOT NULL,
                              COMPETENCIA VARCHAR2(255 CHAR)   NOT NULL
);
