CREATE TABLE OBJETIVO_RESKI (
                                ID        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                CARGO     VARCHAR2(150 CHAR)   NOT NULL,
                                AREA      VARCHAR2(150 CHAR)   NOT NULL,
                                DESCRICAO VARCHAR2(4000 CHAR)  NOT NULL,
                                DEMANDA   VARCHAR2(4000 CHAR)  NOT NULL
);
